name: build
on:
    push:
        branches:
            - develop
            - master
            - main
    pull_request: ~
env:
    APP_SECRET: '633f5aca7d8e6008704f6953de3w959j'
jobs:
    build:
        strategy:
            matrix:
                php-versions: ['8.2']
        name: Continues Integration (PHP ${{ matrix.php-versions }})
        runs-on: ubuntu-latest
        steps:
            # Checkout project
            - name: Checkout
              uses: actions/checkout@v2
            # Install php & composer
            - name: Setup PHP, extensions and composer with shivammathur/setup-php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, xml, ctype, iconv, intl, pdo, pgsql, dom, filter, gd, iconv, json, mbstring, pdo
              env:
                  update: true
            - name: Check PHP Version
              run: php -v
            # Composer
            - name: Validate composer.json and composer.lock
              run: composer validate
            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install Composer dependencies
              run: composer install
            # Coding standard
            - name: Coding standards checks (php_codesniffer)
              run: bin/phpcs -n --colors --error-severity=1
            # PhpUnit
            - name: PhpUnit
              run: bin/simple-phpunit
